* SPICE netlist generated by Yosys 0.46 (git sha1 e97731b9d, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3)

.SUBCKT sar_logic comp_in clk dig_out.0 dig_out.1 dig_out.2 dig_out.3 dig_out.4 dig_out.5 dig_out.6 dig_out.7 sample dac_in.0 dac_in.1 dac_in.2 dac_in.3 dac_in.4 dac_in.5 dac_in.6 dac_in.7
X0 count.0 1 NOT
X1 count.1 2 NOT
X2 count.2 3 NOT
X3 count.3 4 NOT
X4 dac_in.4 5 NOT
X5 comp_in 6 NOT
X6 count.1 count.2 7 NOR
X7 7 8 NOT
X8 count.0 4 9 NOR
X9 1 count.3 10 NAND
X10 8 10 11 NOR
X11 7 9 12 NAND
X12 dac_in.0 11 13 NAND
X13 dig_out.0 12 14 NAND
X14 13 14 15.0 NAND
X15 dac_in.1 11 16 NAND
X16 dig_out.1 12 17 NAND
X17 16 17 15.1 NAND
X18 dac_in.2 11 18 NAND
X19 dig_out.2 12 19 NAND
X20 18 19 15.2 NAND
X21 dac_in.3 11 20 NAND
X22 dig_out.3 12 21 NAND
X23 20 21 15.3 NAND
X24 dac_in.4 11 22 NAND
X25 dig_out.4 12 23 NAND
X26 22 23 15.4 NAND
X27 dac_in.5 11 24 NAND
X28 dig_out.5 12 25 NAND
X29 24 25 15.5 NAND
X30 dac_in.6 11 26 NAND
X31 dig_out.6 12 27 NAND
X32 26 27 15.6 NAND
X33 dac_in.7 11 28 NAND
X34 dig_out.7 12 29 NAND
X35 28 29 15.7 NAND
X36 count.1 count.3 30 NAND
X37 count.2 count.3 31 NAND
X38 4 7 32 NOR
X39 32 33 NOT
X40 1 33 34 NAND
X41 count.0 32 35 NAND
X42 34 35 36.0 NAND
X43 count.0 count.1 37 NOR
X44 37 38 NOT
X45 1 2 39 NOR
X46 count.0 count.1 40 NAND
X47 37 39 41 NOR
X48 4 41 42 NAND
X49 30 42 36.1 NAND
X50 count.2 39 43 NOR
X51 count.2 count.3 44 NOR
X52 3 4 45 NAND
X53 31 39 46 NAND
X54 44 46 47 NOR
X55 43 47 36.2 NOR
X56 3 count.3 48 NOR
X57 count.2 4 49 NAND
X58 2 49 50 NOR
X59 count.1 48 51 NAND
X60 39 48 52 NAND
X61 9 32 53 NOR
X62 12 33 54 NAND
X63 52 53 36.3 NAND
X64 dac_in.0 54 55 NAND
X65 52 55 56.0 NAND
X66 dac_in.1 54 57 NAND
X67 count.0 6 58 NAND
X68 58 59 NOT
X69 50 58 60 NAND
X70 57 60 56.1 NAND
X71 dac_in.2 36.3 61 NAND
X72 2 comp_in 62 NOR
X73 49 62 63 NOR
X74 41 63 64 NAND
X75 61 64 56.2 NAND
X76 51 53 65 NAND
X77 dac_in.3 65 66 NAND
X78 count.1 59 67 NOR
X79 48 67 68 NAND
X80 66 68 56.3 NAND
X81 1 4 69 NOR
X82 7 69 70 NAND
X83 49 53 71 NAND
X84 count.3 38 72 NOR
X85 5 72 73 NOR
X86 71 73 74 NAND
X87 40 45 75 NOR
X88 comp_in 37 76 NAND
X89 49 76 77 NOR
X90 75 77 78 NOR
X91 74 78 56.4 NAND
X92 dac_in.5 71 79 NAND
X93 2 45 80 NOR
X94 58 80 81 NAND
X95 79 81 56.5 NAND
X96 10 43 82 NAND
X97 dac_in.6 82 83 NAND
X98 45 62 84 NOR
X99 41 84 85 NAND
X100 83 85 56.6 NAND
X101 7 10 86 NAND
X102 dac_in.7 86 87 NAND
X103 44 67 88 NAND
X104 87 88 56.7 NAND
X105 sample 32 89 NAND
X106 70 89 90 NAND
X107 clk 15.0 dig_out.0 DFF
X108 clk 15.1 dig_out.1 DFF
X109 clk 15.2 dig_out.2 DFF
X110 clk 15.3 dig_out.3 DFF
X111 clk 15.4 dig_out.4 DFF
X112 clk 15.5 dig_out.5 DFF
X113 clk 15.6 dig_out.6 DFF
X114 clk 15.7 dig_out.7 DFF
X115 clk 90 sample DFF
X116 clk 56.0 dac_in.0 DFF
X117 clk 56.1 dac_in.1 DFF
X118 clk 56.2 dac_in.2 DFF
X119 clk 56.3 dac_in.3 DFF
X120 clk 56.4 dac_in.4 DFF
X121 clk 56.5 dac_in.5 DFF
X122 clk 56.6 dac_in.6 DFF
X123 clk 56.7 dac_in.7 DFF
X124 clk 36.0 count.0 DFF
X125 clk 36.1 count.1 DFF
X126 clk 36.2 count.2 DFF
X127 clk 36.3 count.3 DFF
.ENDS sar_logic

************************
* end of SPICE netlist *
************************

