/* Generated by Yosys 0.46 (git sha1 e97731b9d, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* cells_not_processed =  1  *)
(* src = "sar_logic.v:1.1-66.10" *)
module sar_logic(comp_in, clk, dig_out, sample, dac_in);
  (* src = "sar_logic.v:11.2-64.5" *)
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  (* force_downto = 32'd1 *)
  (* src = "sar_logic.v:0.0-0.0|sar_logic.v:12.3-63.10|/foss/tools/yosys/bin/../share/yosys/techmap.v:576.21-576.22" *)
  wire [3:0] _087_;
  (* force_downto = 32'd1 *)
  (* src = "sar_logic.v:0.0-0.0|sar_logic.v:12.3-63.10|/foss/tools/yosys/bin/../share/yosys/techmap.v:576.21-576.22" *)
  wire [7:0] _088_;
  (* force_downto = 32'd1 *)
  (* src = "sar_logic.v:0.0-0.0|sar_logic.v:12.3-63.10|/foss/tools/yosys/bin/../share/yosys/techmap.v:576.21-576.22" *)
  wire _089_;
  (* src = "sar_logic.v:3.8-3.11" *)
  input clk;
  wire clk;
  (* src = "sar_logic.v:2.8-2.15" *)
  input comp_in;
  wire comp_in;
  (* init = 4'h9 *)
  (* src = "sar_logic.v:9.12-9.17" *)
  wire [3:0] count;
  (* src = "sar_logic.v:6.19-6.25" *)
  output [7:0] dac_in;
  wire [7:0] dac_in;
  (* src = "sar_logic.v:4.19-4.26" *)
  output [7:0] dig_out;
  wire [7:0] dig_out;
  (* src = "sar_logic.v:5.13-5.19" *)
  output sample;
  wire sample;
  NOT _090_ (
    .A(count[0]),
    .Y(_042_)
  );
  NOT _091_ (
    .A(count[1]),
    .Y(_043_)
  );
  NOT _092_ (
    .A(count[2]),
    .Y(_044_)
  );
  NOT _093_ (
    .A(count[3]),
    .Y(_045_)
  );
  NOT _094_ (
    .A(dac_in[4]),
    .Y(_046_)
  );
  NOT _095_ (
    .A(comp_in),
    .Y(_047_)
  );
  NOR _096_ (
    .A(count[1]),
    .B(count[2]),
    .Y(_048_)
  );
  NOT _097_ (
    .A(_048_),
    .Y(_049_)
  );
  NOR _098_ (
    .A(count[0]),
    .B(_045_),
    .Y(_050_)
  );
  NAND _099_ (
    .A(_042_),
    .B(count[3]),
    .Y(_051_)
  );
  NOR _100_ (
    .A(_049_),
    .B(_051_),
    .Y(_052_)
  );
  NAND _101_ (
    .A(_048_),
    .B(_050_),
    .Y(_053_)
  );
  NAND _102_ (
    .A(dac_in[0]),
    .B(_052_),
    .Y(_054_)
  );
  NAND _103_ (
    .A(dig_out[0]),
    .B(_053_),
    .Y(_055_)
  );
  NAND _104_ (
    .A(_054_),
    .B(_055_),
    .Y(_000_[0])
  );
  NAND _105_ (
    .A(dac_in[1]),
    .B(_052_),
    .Y(_056_)
  );
  NAND _106_ (
    .A(dig_out[1]),
    .B(_053_),
    .Y(_057_)
  );
  NAND _107_ (
    .A(_056_),
    .B(_057_),
    .Y(_000_[1])
  );
  NAND _108_ (
    .A(dac_in[2]),
    .B(_052_),
    .Y(_058_)
  );
  NAND _109_ (
    .A(dig_out[2]),
    .B(_053_),
    .Y(_059_)
  );
  NAND _110_ (
    .A(_058_),
    .B(_059_),
    .Y(_000_[2])
  );
  NAND _111_ (
    .A(dac_in[3]),
    .B(_052_),
    .Y(_060_)
  );
  NAND _112_ (
    .A(dig_out[3]),
    .B(_053_),
    .Y(_061_)
  );
  NAND _113_ (
    .A(_060_),
    .B(_061_),
    .Y(_000_[3])
  );
  NAND _114_ (
    .A(dac_in[4]),
    .B(_052_),
    .Y(_062_)
  );
  NAND _115_ (
    .A(dig_out[4]),
    .B(_053_),
    .Y(_063_)
  );
  NAND _116_ (
    .A(_062_),
    .B(_063_),
    .Y(_000_[4])
  );
  NAND _117_ (
    .A(dac_in[5]),
    .B(_052_),
    .Y(_064_)
  );
  NAND _118_ (
    .A(dig_out[5]),
    .B(_053_),
    .Y(_065_)
  );
  NAND _119_ (
    .A(_064_),
    .B(_065_),
    .Y(_000_[5])
  );
  NAND _120_ (
    .A(dac_in[6]),
    .B(_052_),
    .Y(_066_)
  );
  NAND _121_ (
    .A(dig_out[6]),
    .B(_053_),
    .Y(_067_)
  );
  NAND _122_ (
    .A(_066_),
    .B(_067_),
    .Y(_000_[6])
  );
  NAND _123_ (
    .A(dac_in[7]),
    .B(_052_),
    .Y(_068_)
  );
  NAND _124_ (
    .A(dig_out[7]),
    .B(_053_),
    .Y(_069_)
  );
  NAND _125_ (
    .A(_068_),
    .B(_069_),
    .Y(_000_[7])
  );
  NAND _126_ (
    .A(count[1]),
    .B(count[3]),
    .Y(_070_)
  );
  NAND _127_ (
    .A(count[2]),
    .B(count[3]),
    .Y(_071_)
  );
  NOR _128_ (
    .A(_045_),
    .B(_048_),
    .Y(_072_)
  );
  NOT _129_ (
    .A(_072_),
    .Y(_073_)
  );
  NAND _130_ (
    .A(_042_),
    .B(_073_),
    .Y(_074_)
  );
  NAND _131_ (
    .A(count[0]),
    .B(_072_),
    .Y(_075_)
  );
  NAND _132_ (
    .A(_074_),
    .B(_075_),
    .Y(_087_[0])
  );
  NOR _133_ (
    .A(count[0]),
    .B(count[1]),
    .Y(_076_)
  );
  NOT _134_ (
    .A(_076_),
    .Y(_077_)
  );
  NOR _135_ (
    .A(_042_),
    .B(_043_),
    .Y(_078_)
  );
  NAND _136_ (
    .A(count[0]),
    .B(count[1]),
    .Y(_079_)
  );
  NOR _137_ (
    .A(_076_),
    .B(_078_),
    .Y(_080_)
  );
  NAND _138_ (
    .A(_045_),
    .B(_080_),
    .Y(_081_)
  );
  NAND _139_ (
    .A(_070_),
    .B(_081_),
    .Y(_087_[1])
  );
  NOR _140_ (
    .A(count[2]),
    .B(_078_),
    .Y(_082_)
  );
  NOR _141_ (
    .A(count[2]),
    .B(count[3]),
    .Y(_083_)
  );
  NAND _142_ (
    .A(_044_),
    .B(_045_),
    .Y(_084_)
  );
  NAND _143_ (
    .A(_071_),
    .B(_078_),
    .Y(_085_)
  );
  NOR _144_ (
    .A(_083_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _145_ (
    .A(_082_),
    .B(_086_),
    .Y(_087_[2])
  );
  NOR _146_ (
    .A(_044_),
    .B(count[3]),
    .Y(_001_)
  );
  NAND _147_ (
    .A(count[2]),
    .B(_045_),
    .Y(_002_)
  );
  NOR _148_ (
    .A(_043_),
    .B(_002_),
    .Y(_003_)
  );
  NAND _149_ (
    .A(count[1]),
    .B(_001_),
    .Y(_004_)
  );
  NAND _150_ (
    .A(_078_),
    .B(_001_),
    .Y(_005_)
  );
  NOR _151_ (
    .A(_050_),
    .B(_072_),
    .Y(_006_)
  );
  NAND _152_ (
    .A(_053_),
    .B(_073_),
    .Y(_007_)
  );
  NAND _153_ (
    .A(_005_),
    .B(_006_),
    .Y(_087_[3])
  );
  NAND _154_ (
    .A(dac_in[0]),
    .B(_007_),
    .Y(_008_)
  );
  NAND _155_ (
    .A(_005_),
    .B(_008_),
    .Y(_088_[0])
  );
  NAND _156_ (
    .A(dac_in[1]),
    .B(_007_),
    .Y(_009_)
  );
  NAND _157_ (
    .A(count[0]),
    .B(_047_),
    .Y(_010_)
  );
  NOT _158_ (
    .A(_010_),
    .Y(_011_)
  );
  NAND _159_ (
    .A(_003_),
    .B(_010_),
    .Y(_012_)
  );
  NAND _160_ (
    .A(_009_),
    .B(_012_),
    .Y(_088_[1])
  );
  NAND _161_ (
    .A(dac_in[2]),
    .B(_087_[3]),
    .Y(_013_)
  );
  NOR _162_ (
    .A(_043_),
    .B(comp_in),
    .Y(_014_)
  );
  NOR _163_ (
    .A(_002_),
    .B(_014_),
    .Y(_015_)
  );
  NAND _164_ (
    .A(_080_),
    .B(_015_),
    .Y(_016_)
  );
  NAND _165_ (
    .A(_013_),
    .B(_016_),
    .Y(_088_[2])
  );
  NAND _166_ (
    .A(_004_),
    .B(_006_),
    .Y(_017_)
  );
  NAND _167_ (
    .A(dac_in[3]),
    .B(_017_),
    .Y(_018_)
  );
  NOR _168_ (
    .A(count[1]),
    .B(_011_),
    .Y(_019_)
  );
  NAND _169_ (
    .A(_001_),
    .B(_019_),
    .Y(_020_)
  );
  NAND _170_ (
    .A(_018_),
    .B(_020_),
    .Y(_088_[3])
  );
  NOR _171_ (
    .A(_042_),
    .B(_045_),
    .Y(_021_)
  );
  NAND _172_ (
    .A(_048_),
    .B(_021_),
    .Y(_022_)
  );
  NAND _173_ (
    .A(_002_),
    .B(_006_),
    .Y(_023_)
  );
  NOR _174_ (
    .A(count[3]),
    .B(_077_),
    .Y(_024_)
  );
  NOR _175_ (
    .A(_046_),
    .B(_024_),
    .Y(_025_)
  );
  NAND _176_ (
    .A(_023_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _177_ (
    .A(_079_),
    .B(_084_),
    .Y(_027_)
  );
  NAND _178_ (
    .A(comp_in),
    .B(_076_),
    .Y(_028_)
  );
  NOR _179_ (
    .A(_002_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _180_ (
    .A(_027_),
    .B(_029_),
    .Y(_030_)
  );
  NAND _181_ (
    .A(_026_),
    .B(_030_),
    .Y(_088_[4])
  );
  NAND _182_ (
    .A(dac_in[5]),
    .B(_023_),
    .Y(_031_)
  );
  NOR _183_ (
    .A(_043_),
    .B(_084_),
    .Y(_032_)
  );
  NAND _184_ (
    .A(_010_),
    .B(_032_),
    .Y(_033_)
  );
  NAND _185_ (
    .A(_031_),
    .B(_033_),
    .Y(_088_[5])
  );
  NAND _186_ (
    .A(_051_),
    .B(_082_),
    .Y(_034_)
  );
  NAND _187_ (
    .A(dac_in[6]),
    .B(_034_),
    .Y(_035_)
  );
  NOR _188_ (
    .A(_084_),
    .B(_014_),
    .Y(_036_)
  );
  NAND _189_ (
    .A(_080_),
    .B(_036_),
    .Y(_037_)
  );
  NAND _190_ (
    .A(_035_),
    .B(_037_),
    .Y(_088_[6])
  );
  NAND _191_ (
    .A(_048_),
    .B(_051_),
    .Y(_038_)
  );
  NAND _192_ (
    .A(dac_in[7]),
    .B(_038_),
    .Y(_039_)
  );
  NAND _193_ (
    .A(_083_),
    .B(_019_),
    .Y(_040_)
  );
  NAND _194_ (
    .A(_039_),
    .B(_040_),
    .Y(_088_[7])
  );
  NAND _195_ (
    .A(sample),
    .B(_072_),
    .Y(_041_)
  );
  NAND _196_ (
    .A(_022_),
    .B(_041_),
    .Y(_089_)
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _197_ (
    .C(clk),
    .D(_000_[0]),
    .Q(dig_out[0])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _198_ (
    .C(clk),
    .D(_000_[1]),
    .Q(dig_out[1])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _199_ (
    .C(clk),
    .D(_000_[2]),
    .Q(dig_out[2])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _200_ (
    .C(clk),
    .D(_000_[3]),
    .Q(dig_out[3])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _201_ (
    .C(clk),
    .D(_000_[4]),
    .Q(dig_out[4])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _202_ (
    .C(clk),
    .D(_000_[5]),
    .Q(dig_out[5])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _203_ (
    .C(clk),
    .D(_000_[6]),
    .Q(dig_out[6])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _204_ (
    .C(clk),
    .D(_000_[7]),
    .Q(dig_out[7])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _205_ (
    .C(clk),
    .D(_089_),
    .Q(sample)
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _206_ (
    .C(clk),
    .D(_088_[0]),
    .Q(dac_in[0])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _207_ (
    .C(clk),
    .D(_088_[1]),
    .Q(dac_in[1])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _208_ (
    .C(clk),
    .D(_088_[2]),
    .Q(dac_in[2])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _209_ (
    .C(clk),
    .D(_088_[3]),
    .Q(dac_in[3])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _210_ (
    .C(clk),
    .D(_088_[4]),
    .Q(dac_in[4])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _211_ (
    .C(clk),
    .D(_088_[5]),
    .Q(dac_in[5])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _212_ (
    .C(clk),
    .D(_088_[6]),
    .Q(dac_in[6])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _213_ (
    .C(clk),
    .D(_088_[7]),
    .Q(dac_in[7])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _214_ (
    .C(clk),
    .D(_087_[0]),
    .Q(count[0])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _215_ (
    .C(clk),
    .D(_087_[1]),
    .Q(count[1])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _216_ (
    .C(clk),
    .D(_087_[2]),
    .Q(count[2])
  );
  (* src = "sar_logic.v:11.2-64.5" *)
  DFF _217_ (
    .C(clk),
    .D(_087_[3]),
    .Q(count[3])
  );
endmodule
